<?php

/**
 *
 * @file
 * Primary module hooks for commerce formatage module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */
use Drupal\Core\Form\FormStateInterface;
use Drupal\commerceformatage\CommerceformatageAjax;
use Drupal\Core\Url;

/**
 * Alteration du processus du cehckout.
 *
 * @param array $form
 * @param FormStateInterface $form_state
 * @param string $form_id
 */
function commerceformatage_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  // dump($form_id);
  if (str_contains($form_id, 'commerce_checkout_flow')) {
    $form['#attributes']['class'][] = 'with-tablet mx-auto my-5';
    /**
     * Durant l'etape 'step_id:order_information', on met le paiement à la fin
     * car les informations d'expeditions qui sont en general rempli.
     * Celui de paiement n'etant donc qu'on copie.
     */
    if (!empty($form['#step_id']) && $form['#step_id'] == 'order_information') {
      // meme s'il nya qu'un seule methode de paiement on l'affiche à
      // l'utilisateur.
      if (!empty($form['payment_information']['payment_method']['#options']) && count($form['payment_information']['payment_method']['#options']) == 1)
        $form['payment_information']['payment_method']['#access'] = TRUE;
      // $form['payment_information']['#weight'] = 20;
    }
    /**
     * Bug rencontrer sur la desactivation d'une methode livraison en fonction
     * de la methode de livraison.
     * # Scenario
     * Si l'on desactive une mthode de livraison en fonction de la methode de
     * livraison, cela fonctionne uniquement dans le chargement de la page mais
     * pas via ajax.
     * Lorqu'on va selectionner une autre methode, le formulaire ajax en place
     * ne recharge pas le block Shipping.
     */
    if (!empty($form['payment_information']['payment_method']['#ajax']['callback'])) {
      // On a un bug voir la tache #831. cela ne regle pas le bug car cette
      // action s'effectue une foix le formulaire construit,i.e une foix les
      // methodes de livraison valideés.
      // $order = CommerceformatageAjax::getOrderFromFrom($form_state);
      // $payment_gateway = $order->get('payment_gateway')->getValue();
      // if (!$payment_gateway) {
      // $payment_options = $form['payment_information']['#payment_options'];
      // $value = $form_state->getValue([
      // 'payment_information',
      // 'payment_method'
      // ]);
      // if ($value) {
      // /**
      // *
      // * @var \Drupal\commerce_payment\PaymentOption $payment_option
      // */
      // $payment_option = $payment_options[$value];
      // }
      // else {
      // $payment_option = reset($payment_options);
      // }
      // if ($payment_option) {
      // $order->set('payment_gateway', $payment_option->getPaymentGatewayId());
      // $order->save();
      // }
      // }
      // //////////////////////////////////
      // On va pre-sauvegarder la methode de paiement. En attendant la
      // resolution du bug :
      // https://www.drupal.org/project/commerce_shipping/issues/3226851
      $form['payment_information']['payment_method']['#element_validate'][] = [
        CommerceformatageAjax::class,
        'payment_method_callback_validate'
      ];
      // On definit un nouveau callback afin de mettre à jour les methodes de
      // shipping quand les methodes de payement est modifié.
      $form['payment_information']['payment_method']['#ajax']['callback'] = [
        CommerceformatageAjax::class,
        'commerce_checkout_flow_callback'
      ];
    }
  }
}

/**
 * implement hook_element_info_alter()
 */
// function commerceformatage_element_info_alter(array &$info) {
// dump($info);
// }

/**
 * Implement hook_preprocess_page
 */
function commerceformatage_preprocess_page(&$variables) {
  $loggin = \Drupal::currentUser()->id();
  if (!$loggin) {
    // Cette librairie permet de faire des liens ajax.
    $variables['page']['content']['#attached']['library'][] = 'core/drupal.ajax';
  }
}

/**
 * Alteration de l'etape de login au niveau du checkout.
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param int $form_id
 */
// function
// commerceformatage_form_commerce_order_item_add_to_cart_form_alter(&$form,
// FormStateInterface $form_state, $form_id) {
// }

/**
 * Alteration du formulaire d'ajout au panier.
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param int $form_id
 */
function commerceformatage_form_commerce_order_item_add_to_cart_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $configs = \Drupal::config("commerceformatage.settings")->getRawData();
  if (!empty($configs['commerce_buy_now']['enable']))
    $form['actions']['commerce_buy_now'] = [
      '#type' => 'submit',
      '#value' => t($configs['commerce_buy_now']['text']),
      '#weight' => 10,
      '#submit' => [
        '_commerceformatage_buy_now_submit'
      ],
      '#attributes' => [
        'class' => explode(" ", $configs['commerce_buy_now']['class'])
      ]
    ];
  // Si l'utilisateur a selectionner un variante:
  if ($form_state->has('selected_variation')) {
    $entityTypeManger = \Drupal::entityTypeManager();
    $selected_variation = $form_state->get('selected_variation');
    /** @var \Drupal\commerce_product\Entity\ProductVariationInterface $selected_variation */
    $commerce_product_variation = $entityTypeManger->getStorage('commerce_product_variation')->load($selected_variation);
  }
  else {
    $commerce_product_variation = $form_state->get('product')->getDefaultVariation();
  }
  // On verifie si le produit est toujours definit comme etant toujours en
  // stock.
  /**
   *
   * @var \Drupal\commerce_stock\AlwaysInStockService $always_in_stock_service
   */
  $always_in_stock_service = \Drupal::service("commerce_stock.always_in_stock_service");
  $InStock = $always_in_stock_service->getStockChecker()->getIsAlwaysInStock($commerce_product_variation);
  if (!$InStock) {
    /**
     *
     * @var \Drupal\commerce_stock_local\LocalStockChecker $LocalStockChecker
     */
    $LocalStockChecker = \Drupal::service('commerce_stock.local_stock_checker');
    $locations = \Drupal\commerce_stock_local\Entity\StockLocation::loadMultiple();
    $InStock = $LocalStockChecker->getTotalAvailableStockLevel($commerce_product_variation, $locations) > 0;
  }
  $form['commerce_product_variation_id'] = [
    '#type' => 'hidden',
    '#value' => $commerce_product_variation->id()
  ];
  // disbled default submit
  $form['actions']['submit']['#access'] = false;
  // add custom submit (utilise ajax)
  $css_add_to_cart = isset($configs['commerce_style']['css_add_to_cart']) ? $configs['commerce_style']['css_add_to_cart'] : 'btn btn-primary';
  $custom_submit = [
    '#theme' => 'commerceformatage_submit_commerce',
    '#attributes' => [
      'class' => [
        'commerceformatage-button-add-to-cart',
        $css_add_to_cart
      ],
      'disabled' => !$InStock
    ],
    '#value' => $InStock ? $form['actions']['submit']['#value'] : t("Coming soon")
  ];
  /**
   *
   * @var \Drupal\commerce_cart\Form\AddToCartForm $formAddCart
   */
  $formAddCart = $form_state->getFormObject();
  /**
   *
   * @var \Drupal\commerce_order\Entity\OrderItem $entity
   */
  $entity = $formAddCart->getEntity();
  // dump($entity->bundle());
  if (!empty($form['quantity'])) {
    $quantity = $form['quantity'];
    if (!empty($quantity['widget'][0]['value']))
      $quantity['widget'][0]['value']['#attributes']['disabled'] = !$InStock;
    unset($form['quantity']);
    $form['actions']['custom_submit'] = $custom_submit;
    $actions = $form['actions'];
    unset($form['actions']);
    $css_container = isset($configs['commerce_style']['css_container']) ? $configs['commerce_style']['css_container'] : 'row no-gutters g-2 d-flex align-items-end';
    $css_container_qty = isset($configs['commerce_style']['css_container_qty']) ? $configs['commerce_style']['css_container_qty'] : 'col-3';
    $css_container_add_to_cart = isset($configs['commerce_style']['css_container_add_to_cart']) ? $configs['commerce_style']['css_container_add_to_cart'] : 'col';
    $container = [
      '#type' => 'html_tag',
      '#tag' => 'div',
      '#attributes' => [
        'class' => [
          $css_container
        ]
      ],
      [
        '#type' => 'html_tag',
        '#tag' => 'div',
        '#attributes' => [
          'class' => [
            $css_container_qty
          ]
        ],
        $quantity
      ],
      [
        '#type' => 'html_tag',
        '#tag' => 'div',
        '#attributes' => [
          'class' => [
            $css_container_add_to_cart
          ]
        ],
        $actions
      ]
    ];
    $form['contain-qty-add'] = $container;
  }
  else {
    $form['actions']['custom_submit'] = $custom_submit;
    if (!empty($form['actions']['submit']))
      unset($form['actions']['submit']);
  }
}

/**
 *
 * @param array $form
 * @param FormStateInterface $form_state
 * @param string $form_id
 */
function commerceformatage_form_commerce_checkout_flow_multistep_default_alter(&$form, FormStateInterface $form_state, $form_id) {
  // dump();
  if (!empty($form['login']['#attributes'])) {
    $form['login']['#attributes']['class'][] = 'd-flex';
    $form['login']['#attributes']['class'][] = 'flex-wrap';
  }
  if (!empty($form['login']['guest']['continue'])) {
    $form['login']['guest']['continue']['#attributes']['data-twig-suggestion'] = 'commerce_continue';
    $form['login']['guest']['continue']['#attributes']['class'][] = 'btn';
    $form['login']['guest']['continue']['#attributes']['class'][] = 'btn-outline-primary';
    $form['login']['guest']['continue']['#attributes']['class'][] = 'mt-md-5';
    $form['login']['guest']['continue']['#attributes']['class'][] = 'btn-lg';
  }
  if (!empty($form['login']['returning_customer']['submit'])) {
    $form['login']['returning_customer']['submit']['#attributes']['data-twig-suggestion'] = 'commerce_returning_customer';
    $form['login']['returning_customer']['submit']['#attributes']['class'][] = 'btn';
    $form['login']['returning_customer']['submit']['#attributes']['class'][] = 'btn-primary';
    $form['login']['returning_customer']['submit']['#attributes']['class'][] = 'me-5';
  }
}

/**
 * Permet de surcharger la page panier.
 *
 * @param array $form
 * @param FormStateInterface $form_state
 * @param integer $form_id
 */
function commerceformatage_form_views_form_commerce_cart_form_default_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add class container
  if (!isset($form['#attributes']['class'])) {
    $form['#attributes']['class'] = [];
  }
  $form['#attributes']['class'][] = 'container';
  $form['#attributes']['class'][] = 'my-5';
  $form['#attributes']['class'][] = 'table-td-align-middle';
  $form['#attributes']['class'][] = 'cart-form';
  // formatage des bouttons.
  if (!empty($form['actions']['submit']) && !empty($form['actions']['checkout'])) {
    // button update
    $form['actions']['submit']['#attributes'] = [
      'class' => [
        'w-auto',
        'd-flex',
        'btn',
        'btn-outline-secondary'
      ],
      'data-twig-suggestion' => 'commerce_update'
    ];
    // Button checkout
    $form['actions']['checkout']['#attributes'] = [
      'class' => [
        'w-auto',
        'fw-bold',
        'btn',
        'btn-outline-primary'
      ],
      'data-twig-suggestion' => 'commerce_checkout'
    ];
    //
    $form['actions']['container'] = [
      '#type' => 'html_tag',
      '#tag' => 'div',
      '#attributes' => [
        'class' => [
          'd-flex',
          'justify-content-between',
          'flex-wrap'
        ]
      ],
      $form['actions']['submit'],
      $form['actions']['checkout']
    ];
    // dump($form['actions']['submit']);
    unset($form['actions']['checkout']);
    unset($form['actions']['submit']);
  }
}

/**
 * implement hook_theme
 *
 * @return string[]|string[][]|string[][][]
 */
function commerceformatage_theme() {
  $hooks['commerceformatage_submit_commerce'] = [
    'preprocess functions' => [
      'template_preprocess_submit_commerce'
    ],
    'render element' => 'element',
    'file' => 'commerceformatage.theme.inc'
  ];
  $hooks['commerceformatage_cart_bloc_count'] = [
    'preprocess functions' => [
      'template_preprocess_commerceformatage_cart_bloc_count'
    ],
    'render element' => 'element',
    'attributes' => null,
    'file' => 'commerceformatage.theme.inc'
  ];
  $hooks['commerceformatage_cart_bloc_count_svgback'] = [
    'preprocess functions' => [
      'template_preprocess_commerceformatage_cart_bloc_count_svgback'
    ],
    'render element' => 'element',
    'file' => 'commerceformatage.theme.inc'
  ];
  $hooks['commerceformatage_cart_svgclose'] = [
    'render element' => 'element'
  ];
  $hooks['commerceformatage_cart_svgremoveitem'] = [
    'render element' => 'element'
  ];
  $hooks['commerceformatage_address_2colonnes'] = [
    'variables' => [
      'col_left' => NULL,
      'col_right' => NULL
    ]
  ];
  return $hooks;
}

/**
 *
 * @param
 *        $suggestions
 * @param array $variables
 */
function commerceformatage_theme_suggestions_input_alter(&$suggestions, array $variables) {
  $element = $variables['element'];
  if (isset($element['#attributes']['data-twig-suggestion'])) {
    $suggestions[] = 'input__' . $element['#type'] . '_' . $element['#attributes']['data-twig-suggestion'];
  }
  else {
    $parents = !empty($element['#parents']) ? $element['#parents'] : null;
    
    if ($parents && in_array('remove_button', $parents)) {
      $suggestions[] = 'input__' . $element['#type'] . '__remove_button';
    }
  }
}

/**
 * Adds an item to the shopping cart and redirects to the checkout page.
 *
 * @param array $form
 *        Nested array of form elements that comprise the form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *        The form state.
 */
function _commerceformatage_buy_now_submit($form, FormStateInterface $form_state) {
  $form_storage = $form_state->getStorage();
  $product = $form_storage['product'];
  
  $product_variation_id = $product->get('variations')->target_id;
  $store_id = $product->get('stores')->target_id;
  $entity_type_manager = \Drupal::entityTypeManager();
  $variation_obj = $entity_type_manager->getStorage('commerce_product_variation')->load($product_variation_id);
  $store = $entity_type_manager->getStorage('commerce_store')->load($store_id);
  
  $cart_provider = \Drupal::service('commerce_cart.cart_provider');
  $cart = $cart_provider->getCart('default', $store);
  
  if (!$cart) {
    $cart = $cart_provider->createCart('default', $store);
  }
  
  $entity_type_manager->getStorage('commerce_order_item_type');
  $cart_manager = \Drupal::service('commerce_cart.cart_manager');
  
  $user_input = $form_state->getUserInput();
  $quantity = isset($user_input['quantity'][0]['value']) && $user_input['quantity'][0]['value'] > 0 ? $user_input['quantity'][0]['value'] : '1';
  
  $cart_manager->addEntity($cart, $variation_obj, $quantity);
  
  $url = Url::fromRoute('commerce_checkout.checkout');
  $form_state->setRedirectUrl($url);
}
